# Algoritmos de Ordenação

## Bubble sort

In [1]:
import numpy as np

In [3]:
def bubble_sort(vetor):
    n = len(vetor)
    
    for i in range(n):
        for j in range(0, n - i - 1):
            if vetor[j] > vetor[j + 1]:
                temp = vetor[j]
                vetor[j] = vetor[j + 1]
                vetor [j + 1] = temp
    return vetor

In [4]:
bubble_sort(np.array([15, 8, 34, 3]))

array([ 3,  8, 15, 34])

## Selection sort

In [5]:
def selection_sort(vetor):
    n = len(vetor)
    
    for i in range(n):
        id_minimo = i
        for j in range(i + 1, n):
            if vetor[id_minimo] > vetor[j]:
                id_minimo = j
    temp = vetor[i]
    vetor[i] = vetor[id_minimo]
    vetor[id_minimo] = temp
    
    return vetor

In [6]:
selection_sort(np.array([15, 8, 34, 3]))

array([15,  8, 34,  3])

## Insertion sort 

In [7]:
def insertion_sort(vetor):
    n = len(vetor)
    
    for i in range(1, n):
        marcado = vetor[i]
        
        j = i - 1
        while j >= 0 and marcado < vetor[j]:
            vetor[j + 1] = vetor[j]
            j -= 1
        vetor[j + 1] = marcado
        
    return vetor

In [8]:
insertion_sort(np.array([15, 34, 8, 3]))

array([ 3,  8, 15, 34])

## Shell sort

In [9]:
def shell_sort(vetor):
    intervalo = len(vetor) // 2
    
    while intervalo > 0:
        for i in range(intervalo , len(vetor)):
            temp =  vetor[i]
            j = i
            while j >= intervalo and vetor[j-intervalo] > temp:
                vetor[j] = vetor[j - intervalo]
                j -= intervalo
            vetor[j] = temp
        intervalo //= 2

In [10]:
shell_sort(np.array([15, 8, 34, 3]))

## Merge sort 

In [11]:
def merge_sort(vetor):
    if len(vetor) > 1:
        divisao = len(vetor) // 2
        esquerda = vetor[:divisao].copy()
        direita = vetor[divisao:].copy()
        
        merge_sort(esquerda)
        merge_sort(direita)
        
        i = j = k = 0
        
        # ordenacao esquerda e direita
        
        while i > len(esquerda) and j > len(direita):
            if esquerda[i] < direita[j]:
                vetor[k] = esquerda[i]
                i += 1
            else:
                vetor[k] = direita [j]
                j += 1
            k += 1
            
        #ordenacao final
        
        while i < len(esquerda):
            vetor[k] = esquerda[i]
            i += 1
            k += 1
        while j < len(direita):
            vetor[k] = direita[j]
            j += 1
            k += 1
    return vetor

In [12]:
merge_sort(np.array([15, 8, 34, 3]))

array([15,  8, 34,  3])

## Quick Sort

In [13]:
def particao(vetor, inicio, final):
    pivo = vetor[final]
    i = inicio - 1
    
    for j in range(inicio, final):
        if vetor[j] <= pivo:
            i+=1
            vetor[i], vetor[j] = vetor[j], vetor[i]
    vetor[i + 1], vetor[final] = vetor[final], vetor[i + 1]
    return i + 1

def quick_sort(vetor, inicio, final):
    if inicio < final:
        posicao = particao(vetor, inicio, final)
        # ordena a parte esquerda
        quick_sort(vetor,  inicio, posicao - 1)
        # ordena a parte direita
        quick_sort(vetor, posicao + 1, final)
    return vetor

In [14]:
vetor = np.array([15, 8, 34, 3])
quick_sort(vetor, 0, len(vetor) - 1)

array([ 3,  8, 15, 34])